### ISSUE TITLE
2.0.14 got much more proble, please upgrade to latest official lantern 2.0.16

### ISSUE THREAD

**Issue by ghost** [kendou/lantern#1]
2.0.14 got much more proble, please upgrade to latest official lantern 2.0.16
now 2.0.14 can not connect to the server. it's hard to visit blocked site.

**Comment by kendou** [comment]
Sure, give me two days.
For the time being you can use the old 2.0.10.

**Comment by kendou** [comment]
Updated to 2.0.16, have a try please.
